# vim: set filetype=tmux :

# change prefix to Ctrl+a
set -gu prefix2
unbind C-a
unbind C-b
set -g prefix C-a

# enable mouse
#set -g mouse on

# set numbering base to 1
set -g base-index 1

# customize status bar
# ''
# '' 
# ''
# ''
# ❐ #S | ↑
# [HEX color tool](https://www.toolhelper.cn/Color/RGBToHex)

set -g status on
set -g status-position bottom
set -g status-style "bg=#282c34,fg=#abb2bf,bold"
set -g window-status-style "fg=#5c6370,bg=#282c34"
set -g window-status-current-style "fg=black,bg=#61afef,bold"

set -g status-left  "#[fg=black,bg=#efb000,bold]❐ #S#[fg=#efb000,bg=#282c34]"
set -g status-right "#[fg=#98c379,bg=#282c34]#[fg=black,bg=#98c379]#{pane_current_path}#[fg=#282c34,bg=#98c379]#[fg=#e5c07b,bg=#282c34]#[fg=black,bg=#e5c07b] %H:%M "
set -g window-status-separator "#[fg=#282c34,bg=#282c34]"
set -g window-status-format "#[fg=#5c6370,bg=#282c34]#I:#W"
set -g window-status-current-format "#[fg=#282c34,bg=#61afef]#[fg=black,bg=#61afef] #I:#W #[fg=#61afef,bg=#282c34]"

#set -g status-left "[#S] "
#set -g status-right "#{@cpu_display} #{@ram_display} | %H:%M"
#set -g status-style "bg=green,fg=black"

set -g history-limit 5000

#bind-key -T prefix - split-window -v
#bind-key -T prefix | split-window -h

bind -r h select-pane -L # move left
bind -r j select-pane -D # move down
bind -r k select-pane -U # move up
bind -r l select-pane -R # move right
bind > swap-pane -D
bind < swap-pane -U

# pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

unbind n
unbind p
bind -r C-h previous-window
bind -r C-l next-window
bind Tab last-window

# choose default shell
#set -g default-shell cmd
set -g default-shell powershell
#set -g default-shell "%USERPROFILE%\scoop\shims\bash.exe"
#set -g default-shell wsl


# ==================
# Plugins
# ==================
set -g @plugin 'psmux-plugins/ppm'
set -g @plugin 'psmux-plugins/psmux-sensible'
#set -g @plugin 'psmux-plugins/psmux-cpu'
#set -g @plugin 'psmux-plugins/psmux-resurrect'
#set -g @plugin 'psmux-plugins/psmux-pain-control'
#set -g @plugin 'psmux-plugins/psmux-theme-gruvbox'

set -g @gruvbox-variant 'dark'
set -g @gruvbox-contrast 'medium'
set -g @gruvbox-show-powerline 'on'
#run-shell 'pwsh -NoProfile -File "%USERPROFILE%\.psmux\plugins\psmux-theme-gruvbox\psmux-theme-gruvbox.ps1"'

# load ppm
run '%USERPROFILE%\.psmux\plugins\ppm\ppm.ps1'

