# change prefix to Ctrl+a
set -gu prefix2
unbind C-a
unbind C-b
set -g prefix C-a

# enable mouse
#set -g mouse on

# set numbering base to 1
set -g base-index 1

# customize status bar
set -g status-left "[#S] "
set -g status-right "%H:%M %d-%b-%y"
set -g status-style "bg=green,fg=black"

set -g history-limit 5000

bind-key -T prefix - split-window -v
bind-key -T prefix | split-window -h

# choose default shell
set -g default-shell cmd
#set -g default-shell powershell
#set -g default-shell "C:\Users\xxx\scoop\shims\bash.exe"
#set -g default-shell wsl
